services:
  postgres:
    image: postgres
    container_name: docs-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  spring-app:
    build:
      context: .
    container_name: spring-app
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/gcs-key.json
    volumes:
      - ./keys/data-analysis-docs-463612-50878d3f875c.json:/secrets/gcs-key.json
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  pgdata:


networks:
  app-network:
    external: true